### PR TITLE
Explicitly check for an undefined value when using the fallback prop

### PR DESCRIPTION
**Pull request by FakeYou**
When a falsy value (for example `0`) is the outcome when using the fallback prop an error would be trown:
```jsx
const Container = styled.div`
  padding: ${styledProps({ none: 0, big: 40 }, 'padding')};
`

Container.defaultProps = {
  padding: 'none',
};
```

Throws:
`[styledProps] Unknown fallback prop provided: padding`

This is because [this line](https://github.com/RafalFilipek/styled-props/blob/da15a8a54c1c2fca1c2032528d87eec32a612197/src/styledProps.js#L27) is false when the value ends up being `0`. In this pull request I've added an explicit check for undefined in this statement.

### CODE REVIEW

**Comment by RafalFilipek** [comment]
Hey! 

Nice catch :)

Can you add test to be sure if we're good with `''`, `0` etc?

**Comment by FakeYou** [comment]
Hey Rafal,

I've added some test to checkout for values containing `''` and `0`. It should all be working fine now. Let me know what you think.

**Comment by RafalFilipek** [comment]
Sweet! 
I'll release new version later today.

Thank you!

**Comment by FakeYou** [comment]
Thanks for merging my pull request, do you mind publishing a new version to npm?

**Comment by RafalFilipek** [comment]
Done :)

**Pull request merged**
